---
- name: Print specific values from nginx config files
  hosts: all
  become: yes
  tasks:
    - name: Read the nginx config files
      command: cat {{ item }}
      register: nginx_config
      ignore_errors: yes
      with_items:
        - /etc/nginx/conf.d/em7ngx_web_ui.conf
        - /etc/nginx/conf.d/em7ngx_em7proxy_web_ui.conf
        - /etc/nginx/conf.d/em7_sladmin.conf
        - /etc/nginx/conf.d/em7webconfig.conf
        - /etc/nginx/conf.d/em7ngx_model_mc_sp.conf

    - name: Extract and print ssl_protocols, ssl_ciphers, and ssl_prefer_server_ciphers
      debug:
        msg: |
          File: {{ item.item }}
          ssl_protocols: "{{ item.stdout | regex_search('ssl_protocols\s+(\S+)', '\\1') }}"
          ssl_ciphers: "{{ item.stdout | regex_search('ssl_ciphers\s+(\S+)', '\\1') }}"
          ssl_prefer_server_ciphers: "{{ item.stdout | regex_search('ssl_prefer_server_ciphers\s+(\S+)', '\\1') }}"
      with_items: "{{ nginx_config.results }}"

      ansible all -m shell -a "grep -E '^(ssl_protocols|ssl_ciphers|ssl_prefer_server_ciphers)' /etc/nginx/conf.d/em7ngx_web_ui.conf /etc/nginx/conf.d/em7ngx_em7proxy_web_ui.conf /etc/nginx/conf.d/em7_sladmin.conf /etc/nginx/conf.d/em7webconfig.conf /etc/nginx/conf.d/em7ngx_model_mc_sp.conf || true" --become

