---
- name: Move previous backups to a new folder during SL1 11.2.2 upgrade
  hosts: localhost
  become: yes
  tasks:
    - name: Create backup folder for 11.2.2
      file:
        path: /home/em7release/backup_11_2_2
        state: directory
        mode: '0755'

    - name: Move backups from upgrade_backup to backup_11_2_2
      command: mv /home/em7release/upgrade_backup/* /home/em7release/backup_11_2_2
      args:
        removes: /home/em7release/upgrade_backup/*
      
    - name: Verify files are moved successfully
      shell: ls /home/em7release/backup_11_2_2
      register: backup_files

    - debug:
        var: backup_files.stdout_lines
