---
- name: Remove specific commented lines from nginx config files
  hosts: hsbc2em7dc50
  become: yes
  tasks:
    - name: Remove commented lines from nginx config files
      lineinfile:
        path: "{{ item }}"
        state: absent
        regexp: '^#\s*(ssl_protocols|ssl_ciphers|ssl_prefer_server_ciphers)'
        backrefs: yes
      with_items:
        - /etc/nginx/conf.d/em7ngx_web_ui.conf
        - /etc/nginx/conf.d/em7ngx_em7proxy_web_ui.conf
        - /etc/nginx/conf.d/em7_sladmin.conf
        - /etc/nginx/conf.d/em7webconfig.conf
        - /etc/nginx/conf.d/em7ngx_model_mc_sp.conf
      ignore_errors: yes
