---
- name: Remove commented SSL lines from NGINX config files
  hosts: all
  tasks:
    - name: Remove commented #ssl_protocols line
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        state: absent
        regexp: '^#ssl_protocols'
      ignore_errors: true
      with_items:
        - /etc/nginx/conf.d/em7ngx_web_ui.conf
        - /etc/nginx/conf.d/em7ngx_em7proxy_web_ui.conf
        - /etc/nginx/conf.d/em7_sladmin.conf
        - /etc/nginx/conf.d/em7webconfig.conf
        - /etc/nginx/conf.d/em7ngx_model_mc_sp.conf

    - name: Remove commented #ssl_ciphers line
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        state: absent
        regexp: '^#ssl_ciphers'
      ignore_errors: true
      with_items:
        - /etc/nginx/conf.d/em7ngx_web_ui.conf
        - /etc/nginx/conf.d/em7ngx_em7proxy_web_ui.conf
        - /etc/nginx/conf.d/em7_sladmin.conf
        - /etc/nginx/conf.d/em7webconfig.conf
        - /etc/nginx/conf.d/em7ngx_model_mc_sp.conf

    - name: Remove commented #ssl_prefer_server_ciphers line
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        state: absent
        regexp: '^#ssl_prefer_server_ciphers'
      ignore_errors: true
      with_items:
        - /etc/nginx/conf.d/em7ngx_web_ui.conf
        - /etc/nginx/conf.d/em7ngx_em7proxy_web_ui.conf
        - /etc/nginx/conf.d/em7_sladmin.conf
        - /etc/nginx/conf.d/em7webconfig.conf
        - /etc/nginx/conf.d/em7ngx_model_mc_sp.conf
